/**
 * WebApplication1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Calendar { 
    readonly calendarType?: string | null;
    readonly description?: string | null;
    calendarBase?: Calendar;
    readonly timeZoneId?: string | null;
    readonly daysExcluded?: Array<string> | null;
    readonly cronExpressionString?: string | null;
    readonly rangeStartingTime?: string | null;
    readonly rangeEndingTime?: string | null;
    readonly invertTimeRange?: boolean | null;
    readonly excludedDates?: Array<string> | null;
    readonly excludedDays?: Array<boolean> | null;
}

