/**
 * WebApplication1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Trigger } from './trigger';
import { JobDetailDto } from './job-detail-dto';
import { Calendar } from './calendar';


export interface CurrentlyExecutingJobDto { 
    jobDetail?: JobDetailDto;
    trigger?: Trigger;
    calendar?: Calendar;
    readonly recovering?: boolean;
    readonly fireTime?: string;
    readonly scheduledFireTime?: string | null;
    readonly previousFireTime?: string | null;
    readonly nextFireTime?: string | null;
}

