/**
 * WebApplication1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TriggerKey } from './trigger-key';
import { JobKey } from './job-key';


export interface ITrigger { 
    key?: TriggerKey;
    jobKey?: JobKey;
    readonly description?: string | null;
    readonly calendarName?: string | null;
    readonly jobDataMap?: { [key: string]: any; } | null;
    readonly finalFireTimeUtc?: string | null;
    readonly misfireInstruction?: number;
    readonly endTimeUtc?: string | null;
    readonly startTimeUtc?: string;
    priority?: number;
    readonly hasMillisecondPrecision?: boolean;
}

