/**
 * WebApplication1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type IntervalUnit = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;

export const IntervalUnit = {
    NUMBER_0: 0 as IntervalUnit,
    NUMBER_1: 1 as IntervalUnit,
    NUMBER_2: 2 as IntervalUnit,
    NUMBER_3: 3 as IntervalUnit,
    NUMBER_4: 4 as IntervalUnit,
    NUMBER_5: 5 as IntervalUnit,
    NUMBER_6: 6 as IntervalUnit,
    NUMBER_7: 7 as IntervalUnit
};

