/**
 * WebApplication1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SchedulerStatisticsDto } from './scheduler-statistics-dto';
import { SchedulerStatus } from './scheduler-status';
import { SchedulerThreadPoolDto } from './scheduler-thread-pool-dto';
import { SchedulerJobStoreDto } from './scheduler-job-store-dto';


export interface SchedulerDto { 
    schedulerInstanceId?: string | null;
    name?: string | null;
    status?: SchedulerStatus;
    threadPool?: SchedulerThreadPoolDto;
    jobStore?: SchedulerJobStoreDto;
    statistics?: SchedulerStatisticsDto;
}
export namespace SchedulerDto {
}


