/**
 * WebApplication1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntervalUnit } from './interval-unit';
import { TimeSpan } from './time-span';
import { DayOfWeek } from './day-of-week';
import { TimeOfDay } from './time-of-day';
import { KeyDto } from './key-dto';


export interface Trigger { 
    readonly triggerType?: string | null;
    key?: KeyDto;
    jobKey?: KeyDto;
    readonly description?: string | null;
    readonly calendarName?: string | null;
    readonly jobDataMap?: { [key: string]: any; } | null;
    readonly misfireInstruction?: number;
    readonly startTimeUtc?: string;
    readonly endTimeUtc?: string | null;
    readonly priority?: number;
    readonly timeZone?: string | null;
    readonly repeatInterval?: number | null;
    repeatIntervalUnit?: IntervalUnit;
    readonly preserveHourOfDayAcrossDaylightSavings?: boolean | null;
    readonly skipDayIfHourDoesNotExist?: boolean | null;
    readonly cronExpressionString?: string | null;
    readonly repeatCount?: number | null;
    startTimeOfDay?: TimeOfDay;
    endTimeOfDay?: TimeOfDay;
    readonly daysOfWeek?: Array<DayOfWeek> | null;
    repeatIntervalTimeSpan?: TimeSpan;
}
export namespace Trigger {
}


