/**
 * WebApplication1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TriggerState = 0 | 1 | 2 | 3 | 4 | 5;

export const TriggerState = {
    NUMBER_0: 0 as TriggerState,
    NUMBER_1: 1 as TriggerState,
    NUMBER_2: 2 as TriggerState,
    NUMBER_3: 3 as TriggerState,
    NUMBER_4: 4 as TriggerState,
    NUMBER_5: 5 as TriggerState
};

