/**
 * WebApplication1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddCalendarRequest } from '../model/models';
import { Calendar } from '../model/models';
import { DeleteCalendarResponse } from '../model/models';
import { NamesDto } from '../model/models';
import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CalendarServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param schedulerName 
     * @param addCalendarRequest 
     */
    addCalendar(schedulerName: string, addCalendarRequest: AddCalendarRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param schedulerName 
     * @param calendarName 
     */
    deleteCalendar(schedulerName: string, calendarName: string, extraHttpRequestParams?: any): Observable<DeleteCalendarResponse>;

    /**
     * 
     * 
     * @param schedulerName 
     * @param calendarName 
     */
    getCalendar(schedulerName: string, calendarName: string, extraHttpRequestParams?: any): Observable<Calendar>;

    /**
     * 
     * 
     * @param schedulerName 
     */
    getCalendarNames(schedulerName: string, extraHttpRequestParams?: any): Observable<NamesDto>;

}
