/**
 * WebApplication1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProblemDetails } from '../model/models';
import { SchedulerContextDto } from '../model/models';
import { SchedulerDto } from '../model/models';
import { SchedulerHeaderDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SchedulerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param schedulerName 
     */
    clear(schedulerName: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    getAllSchedulers(extraHttpRequestParams?: any): Observable<Array<SchedulerHeaderDto>>;

    /**
     * 
     * 
     * @param schedulerName 
     */
    getSchedulerContext(schedulerName: string, extraHttpRequestParams?: any): Observable<SchedulerContextDto>;

    /**
     * 
     * 
     * @param schedulerName 
     */
    getSchedulerDetails(schedulerName: string, extraHttpRequestParams?: any): Observable<SchedulerDto>;

    /**
     * 
     * 
     * @param schedulerName 
     */
    pauseAll(schedulerName: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param schedulerName 
     */
    resumeAll(schedulerName: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param schedulerName 
     * @param waitForJobsToComplete 
     */
    shutdown(schedulerName: string, waitForJobsToComplete?: boolean, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param schedulerName 
     */
    standby(schedulerName: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param schedulerName 
     * @param delayMilliseconds 
     */
    start(schedulerName: string, delayMilliseconds?: number, extraHttpRequestParams?: any): Observable<{}>;

}
